### ISSUE TITLE
30 DAYS REMAIN

### ISSUE THREAD

**Issue by qpfiffer** [qpfiffer/shithouse.tv#22]
![](http://fuck-you-i-cant-die.shithouse.tv/Screenshot-from-2016-02-22-200110.png)

**Comment by dequis** [comment]
:package:

**Comment by cblgh** [comment]
💩 🏠

**Comment by dequis** [comment]
Thank you for your bug report and your interest in helping the shithouse project.

I looked into this issue and reached the conclusion that this is intended behavior, so I'm closing this bug as WONTFIX.
