### ISSUE TITLE
apostrophe in stupid fucking text fucks up

### ISSUE THREAD

**Issue by cblgh** [qpfiffer/shithouse.tv#23]
u've got a bug ('ve got a bug wouldn't be visible if i wrote this as stupid fucking text for a bump)

**Comment by dequis** [comment]
sql injection protection

**Comment by dequis** [comment]
@cblgh 📦

**Comment by dequis** [comment]
![stupid fucking text](https://user-images.githubusercontent.com/94108/28901682-5af4b894-77d0-11e7-8291-668261297125.png)

![works for me](https://user-images.githubusercontent.com/94108/28901715-8fb36cec-77d0-11e7-9605-e639cbe8fc40.png)

**Comment by cblgh** [comment]
http://doesntfuck.shithouse.tv/
fuck this is closed

**Comment by cblgh** [comment]
🖤

**Comment by lykkin** [comment]
were there tests added for this issue?
